# Generated by Django 3.2.25 on 2025-01-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_conact_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
