# Generated by Django 4.2 on 2025-02-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_approach_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='massage',
            new_name='message',
        ),
    ]
